---

# Ansible Requirements File
# https://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files
#
# Install via: ansible-galaxy install -r requirements.yml


# included in senaite_plone.yml
- src: https://github.com/plone/ansible.plone_server
  version: master
  name: plone.plone_server

# included in senaite_haproxy.yml
- name: geerlingguy.haproxy

# included in senaite_nginx.yml
- name: geerlingguy.nginx

# included in senaite_munin.yml
- src: geerlingguy.munin

# included in senaite_postfix.yml
- src: oefenweb.postfix

# included in senaite_security.yml
- src: HanXHX.firewall
