---

plone_initial_password: "admin"
munin_admin_user: "admin"
munin_admin_password: "admin"
haproxy_stats_user: "admin"
haproxy_stats_pass: "admin"
supervisor_http_user: "admin"
supervisor_http_pass: "admin"
firewall_open_tcp_ports: [22, 25, 80, 443]
nginx_keepalive_timeout: "300"
plone_zodb_cache_size: 50000
plone_additional_versions:
  - CairoSVG=1.0.20
  - zc.buildout=
  - setuptools=
